export const state = {
    postsResource: [
        { "id": 1, "title": "Port1", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/3962.jpg", "type": "portfolio", "likedBy": [], comments: [] },
        { "id": 2, "title": "Port2", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/3955.jpg", "type": "portfolio", "likedBy": [], comments: [] },
        { "id": 3, "title": "Port3", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/177.jpg", "type": "portfolio", "likedBy": [], comments: [] },
        { "id": 4, "title": "Port4", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/5357.jpg", "type": "portfolio", "likedBy": [], comments: [] },
        { "id": 5, "title": "Port5", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/3946.jpg", "type": "portfolio", "likedBy": [], comments: [] },
        { "id": 6, "title": "Port6", "descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto quasi nam veniam, ipsa fugiat unde alias reprehenderit error necessitatibus culpa assumenda tempora earum, cumque illo nobis placeat reiciendis! Nisi, pariatur!", "poster": "https://wallpapershome.com/images/pages/ico_h/3945.jpg", "type": "portfolio", "likedBy": [], comments: [] },
    ],
    posts: []
}